### ISSUE TITLE
Pages don't appear on first opening

### ISSUE THREAD

**Issue by maurosbicego** [fancoder/cryptonote-universal-pool#105]
When I open my pool ([http://sumopool.de](http://sumopool.de)), the top bar appears but then there's only the circle. The Infos don't show up. I have to go to an other page to get it working. ([http://sumopool.de/#getting_started](http://sumopool.de/#getting_started) then back to home)
This is very strange..
I hope somebody can help.

**Comment by CerveloFellow** [comment]
I'm getting the same thing.  I have tried running python SimpleHTTPServer and thought that might be the problem but am also getting the issue with lighttpd.  Is there a suggested lightweight webserver that people use for this?

**Comment by maurosbicego** [comment]
I've tried both nginx and apache, but they didn't work.
I've tried to solve it and destroyed my pool 😭. 
So I've installed the Zone117x Pool but that doesn't work. (I can minr on it, but no API) 
So I'll install this Pool again and report back. 

p.s.
@CerveloFellow
Wich server OS are you using? 
Because I was on 14.04 (I think...) and the problem is probably only on 14.04

**Comment by maurosbicego** [comment]
I got the Zone117x Pool working, but the problem with the first site is still here...
I will take a closer look in the next days....

**Comment by CerveloFellow** [comment]
I've got it up and running with lighttpd now.  I changed a lot of settings back and forth and tinkered with permissions on folders.  I'm not exactly sure which changes fixed it, but if you're using lighttpd and you want me to check any configuration on mine, I'm happy to help.

**Comment by maurosbicego** [comment]
It's a problem of the server...
Because I got it working on a normal Webhosting (not VPS)
But I wanna have it on the VPS. 
Could you please send me your config?

**Comment by CerveloFellow** [comment]
server.modules = (
        "mod_access",
        "mod_alias",
        "mod_compress",
        "mod_redirect",
)

server.document-root        = "/home/cryptonote/pool/website/"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html"
 )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html
", "text/plain" )

include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

**Comment by maurosbicego** [comment]
It still doesn't work....

**Comment by maurosbicego** [comment]
@CerveloFellow Could you please send the permission config?

**Comment by CerveloFellow** [comment]
644 root root on lighttpd.conf
755 root root on /etc/lighttpd/

**Comment by maurosbicego** [comment]
I solved it by redirecting the Domain to www and point the www subdomain to another Webserver
