### ISSUE TITLE
Bugs refreshing pool blocks page and payments chart

### ISSUE THREAD

**Issue by fish34** [fancoder/cryptonote-universal-pool#12]
Hello fancoder!
We have noticed that when refreshing Pool Blocks page there is no Info about blocks. You must buck to home page and back.
2nd is thst payments chart showing not correctly, ie its show time reverse.
And want ask you about charts : charts has, price ,difficulty take time from? and hashrate and workers from? it is different time. Last to depends on the server time? and first three from what?
Thanks in advice!

**Comment by fancoder** [comment]
Hi Fish!

Fixed wrong payments chart order & JS error on #pool_blocks.

> And want ask you about charts : charts has, price ,difficulty take time from? and hashrate and workers from? it is different time. Last to depends on the server time? and first three from what?

Check https://github.com/fancoder/cryptonote-universal-pool/blob/master/config.json#L132 you'll see that difficulty, price and profit has different interval & period options than workers and hashrate.

Thank you for bug report!

**Comment by fish34** [comment]
Thank you for answer! Another question, charts  are not updates correctly : hasp price, difficulty. I see that it takes from 'www.cryptonator.com', 443 but its port closed (due to nmap log). And data of charts is old. I understood that update time of charts is differ but not so. For example look at http://monero.xminingpool.com/ 

Its not my pool, but for example.

Maybe there is another way to update charts?

And if you know, can you tell me please, there is a way to apply changes in libs or config.json without restarting a pool?

**Comment by fancoder** [comment]
> Another question, charts  are not updates correctly : hasp price, difficulty. I see that it takes from 'www.cryptonator.com', 443 but its port closed (due to nmap log). And data of charts is old.

What coin is configured on your pool? May be the problem is that cryptonator.org do not support your coin? Can you provide detailed config.json of your pool?

> For example look at http://monero.xminingpool.com/

xminingpool.com admin said that he uses original version of CUP without any code changes. Also he said he uses default values for all charts config options.

> And if you know, can you tell me please, there is a way to apply changes in libs or config.json without restarting a pool?

Unfortunately there is no way to reload pool config without pool restart.

**Comment by fish34** [comment]
So do you think that charts on that pool right? When I wrote to you last value is 6.56 19 august, and at one time our charts updates till 3.28 19 august. It sounds like script can’t take values from cryptonator.org and redis don’t assign new values, no?

**Comment by fancoder** [comment]
> So do you think that charts on that pool right? 

Oh, that's my fault. Sorry. It was a bug in frontend JavaScript. Just fixed it. Thank you so much for report! :+1:

**Comment by fish34** [comment]
Thank you for fix! ;-)

Can you give more info if you know about parameters of confug.json for monero?

"maxDiff": 100000 by default, what it affects on monero mining? Our config have 20000

"targetTime": 100 by default, what it affects on monero mining? Our config have 60

And this 

```
        "maxJump": 100
```

**Comment by fancoder** [comment]
I think this options are ok and do not depends on coin type.

**Comment by fish34** [comment]
Hello!

Sorry for naughty may be you can help with this..

In admin panel at userlist I want highlight specific wallets or add a column with *

For example

<script id="usersListTable" type="text/x-handlebars-template">
        {{#each users}}
        <tr>
                <td><a href="./?wallet={{this.number}}">{{this.number}}</a></td>
                <td data-sort="{{this.wallet.hashrate}}">{{this.readableHashrate}}</td>
                <td data-sort="{{this.wallet.hashes}}">{{this.readableHashes}}</td>
                <td data-sort="{{this.wallet.pending}}">{{this.readablePending}}</td>
                <td data-sort="{{this.wallet.paid}}">{{this.readablePaid}}</td>
                <td data-sort="{{this.wallet.lastShare}}">{{this.timeago}}</td>
                if { {{this.number}}==’41in9Qu8fcQYLMs9Q1GXLsDSMQc4Qov6FMoHjoufHBpEDYtjU991CWdQ9NxbabEgVAPMdwLP4HJJQTbtjQiAwRGALs3ngP4’ 
                <td data-sort="{{this.number}}">*</td>
                        }
        </tr>
        {{/each}}
</script>

But it doesn’t work..

I have download handlebars.min.js but not understand at all how does it works. May be you know how can I insert my condition?

**Comment by fancoder** [comment]
I think you can just add some additional variable 

```
                walletsArray.push({
                    number: wallet,
                    wallet: userData,
                    timeago: $.timeago(new Date(userData.lastShare * 1000).toISOString()),
                    readablePending: getReadableCoins(userData.pending),

                    class: wallet == '41in9Qu8fcQYLMs9Q1GXLsDSMQc4Qov6FMoHjoufHBpEDYtjU991CWdQ9NxbabEgVAPMdwLP4HJJQTbtjQiAwRGALs3ngP4' ? 'highlighted' : '',
```

and 

```
   <tr class="{{this.class}}">
```

.. and specify styles for `highlighted` class

**Comment by fish34** [comment]
Thank you for help! Maybe you know variable userData = wallets[wallet] contain info filed about ip address? I want to out it too in table.

**Comment by fancoder** [comment]
Unfortunly pool do not store client IP in DB.

**Comment by fish34** [comment]
Fancoder, i have observe a trouble autorefreshing pages after sometime. So I must refresh page manually. Do you know what it can be? Maybe high ping from server to hosting? Or its problem in pages?

**Comment by fancoder** [comment]
@fish34 Can you give me the link on that page?

**Comment by fish34** [comment]
Hello! noclaymorefee.com

**Comment by fancoder** [comment]
Everybody, please update to last release version https://github.com/fancoder/cryptonote-universal-pool/releases I think it will fix most bugs.

**Comment by fish34** [comment]
Hello! Today we have update pool, but today we have something like ddos attack from one wallet and differs ip..Messages like bad hash from miner overload cpu for 100%. 

How can I add wallet number to filter that?

I think something like at pool.js

function handleMinerMethod(method, params, ip, portData, sendReply, pushMessage){

```
var miner = connectedMiners[params.id];

            if params.login != '46sSETXrZGT8bupxdc2MAbLe3PMV9nJTRTE5uaFErXFz6ymyzVdH86KDb9TNoG4ny5QLELfopynWeBSMoT1M2Ga8RBkDqTH' {

switch(method){
```

But there is error..Please help if u can..we almost lost our pool :(

**Comment by fancoder** [comment]
@fish34 there is no sense to filter by wallet address because miner can always change it. I recommend you to increase 

```
        "varDiff": {
            "minDiff": 500,
```

 in config.json

**Comment by fish34** [comment]
Thank you fancoder! I'll try it..But yesterday till today morning it was attack at pool from one wallet, i think that is can help..i try filter through iptables and tarpit. And when I use this  filter it is slow down attack but normal users can’t connect later normally

sudo iptables -I INPUT 10 -p tcp -i eth0 -m multiport --dport 3333,5555,7777,8888,9999,80,443 -m state --state NEW -m recent --update --seconds 100--hitcount 10 -j DROP

Do you know how many connections and how many times make a normal pool user?

I don’t understand why doesn’t work this construction:

checkBan: function(validShare){

```
    if (!banningEnabled) return;

    validShare ? this.validShares++ : this.invalidShares++;

    if (this.validShares + this.invalidShares >= config.poolServer.banning.checkThreshold){

        if (this.invalidShares / this.validShares >= config.poolServer.banning.invalidPercent / 100){

            log('warn', logSystem, 'Banned %s@%s', [this.login, this.ip]);

            bannedIPs[this.ip] = Date.now();

            delete connectedMiners[this.id];

            process.send({type: 'banIP', ip: this.ip});
```

When I check databes records thereis no spam wallet,that’s why pool filter doesn’t work?

**Comment by fancoder** [comment]
Everybody please update to last commit https://github.com/fancoder/cryptonote-universal-pool it's very very critical!

**Comment by fish34** [comment]
Hello!

Can I use your pool for blooberry coins? Does it support them? I try with current config and get error in the miner stratum recieve_line_failed and in the pool  

Error: Failed to parse block

```
at Object.BlockTemplate.nextBlob (/home/sa/bbrpool/lib/pool.js:120:23)

at Object.Miner.getJob (/home/sa/bbrpool/lib/pool.js:297:41)

at handleMinerMethod (/home/sa/bbrpool/lib/pool.js:492:28)

at handleMessage (/home/sa/bbrpool/lib/pool.js:600:13)

at Socket.socket.on.on.on.pushMessage (/home/sa/bbrpool/lib/pool.js:654:25)

at Socket.emit (events.js:95:17)

at Socket.<anonymous> (_stream_readable.js:748:14)

at Socket.emit (events.js:92:17)

at emitReadable_ (_stream_readable.js:410:10)

at emitReadable (_stream_readable.js:406:5)
```

Config

{

```
"coin": "boolberry",

"symbol": "BBR",

"coinUnits": 100000000,

"coinDifficultyTarget": 120,



"logging": {

    "files": {

        "level": "info",

        "directory": "logs",

        "flushInterval": 10

    },

    "console": {

        "level": "info",

        "colors": true

    }

},



"poolServer": {

    "enabled": true,

    "clusterForks": "auto",

    "poolAddress": "1J8QZC9ZwcJ78okTd6svoEhntSS8GkCGDR8TfRmYe9RRKurWsVnMTZMUt9DTzVjisY4ciKZioijekFdZn5GHXdSGMLpSU4t",

    "blockRefreshInterval": 1000,

    "minerTimeout": 900,

    "ports": [

        {

            "port": 3333,

            "difficulty": 5000000,

            "desc": "Mid range CPUs"

        }

    ],

    "varDiff": {

        "minDiff": 50000,

        "maxDiff": 100000000,

        "targetTime": 100,

        "retargetTime": 30,

        "variancePercent": 30,

        "maxJump": 20000

    },

    "fixedDiff": {

        "enabled": true,

        "addressSeparator": "."

    },

    "shareTrust": {

        "enabled": true,

        "min": 10,

        "stepDown": 3,

        "threshold": 10,

        "penalty": 30

    },

    "banning": {

        "enabled": true,

        "time": 600,

        "invalidPercent": 25,

        "checkThreshold": 30

    }

},



"payments": {

    "enabled": true,

    "interval": 600,

    "maxAddresses": 50,

    "mixin": 3,

    "transferFee": 5000000,

    "minPayment": 10000000,

    "maxTransactionAmount": 0,

    "denomination": 10000000

},



"blockUnlocker": {

    "enabled": true,

    "interval": 30,

    "depth": 60,

    "poolFee": 0,

    "devDonation": 0,

    "coreDevDonation": 0

},



"api": {

    "enabled": true,

    "hashrateWindow": 600,

    "updateInterval": 5,

    "port": 8117,

    "blocks": 30,

    "payments": 30,

    "password": "pass"

},



"daemon": {

    "host": "127.0.0.1",

    "port": 10102

},



"wallet": {

    "host": "127.0.0.1",

    "port": 8085

},



"redis": {

    "host": "127.0.0.1",

    "port": 6378

},



"monitoring": {

    "daemon": {

        "checkInterval": 60,

        "rpcMethod": "getblockcount"

    },

    "wallet": {

        "checkInterval": 60,

        "rpcMethod": "getbalance"

    }

},



"charts": {

    "pool": {

        "hashrate": {

            "enabled": true,

            "updateInterval": 60,

            "stepInterval": 1800,

            "maximumPeriod": 86400

        },

        "workers": {

            "enabled": true,

            "updateInterval": 60,

            "stepInterval": 1800,

            "maximumPeriod": 86400

        },

        "difficulty": {

            "enabled": true,

            "updateInterval": 1800,

            "stepInterval": 10800,

            "maximumPeriod": 604800

        },

        "price": {

            "enabled": true,

            "updateInterval": 1800,

            "stepInterval": 10800,

            "maximumPeriod": 604800

        },

        "profit": {

            "enabled": true,

            "updateInterval": 1800,

            "stepInterval": 10800,

            "maximumPeriod": 604800

        }

    },

    "user": {

        "hashrate": {

            "enabled": true,

            "updateInterval": 180,

            "stepInterval": 1800,

            "maximumPeriod": 86400

        },

        "payments": {

            "enabled": true

        }

    }

}
```

}

**Comment by fancoder** [comment]
@fish34 I'm not sure CUP will works with Boolberry. Last time I tried there was some errors with Boolberry and I'm not sure that I have enough skill to fix it :(

**Comment by fish34** [comment]
Hi! I have made it, look at http://bbr.unipool.pro/ add it to list please.

**Comment by fancoder** [comment]
@fish34 Done :+1:
