### ISSUE TITLE
About CryptoNight-GPU-Miner-14.6POOL tools FEE problem

### ISSUE THREAD

**Issue by mapleshadow** [fancoder/cryptonote-universal-pool#19]
I've done this tool automatically redirected FEE costs and replace mine own wallet-related code, you feel the need to merge them? 
PS: This tool FEE of 5% 
:)

**Comment by fancoder** [comment]
No, thank you :)

**Comment by mapleshadow** [comment]
:)
2014年8月26日 下午5:26于 "fancoder" notifications@github.com写道：

**Comment by fancoder** [comment]
I think it's just cheating. If you don't like GPU-miner developer fee, so you can use another mining software :)

**Comment by mapleshadow** [comment]
Yes, so I seek your opinions :)
But currently only supports AMD GPU software this software

2014-08-26 19:16 GMT+08:00 fancoder notifications@github.com:

> I think it's just cheating. If you don't like GPU-miner developer fee, so
> you can just use another mining software :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fancoder/cryptonote-universal-pool/issues/19#issuecomment-53405437
> .

## 

—枫影—
