### ISSUE TITLE
not enough outputs to mix

### ISSUE THREAD

**Issue by mapleshadow** [fancoder/cryptonote-universal-pool#21]
9-01 08:58:38 [payments] Started
2014-09-01 08:58:38 [payments] Error with transfer RPC request to wallet daemon {"code":-4,"message":"not enough outputs to mix"}
2014-09-01 08:58:38 [payments] Payments failed to send to {"amount":7944000000000,"address":"ddeExKX3jiVLS7cp3WqakpJ3gRQLFe6aFVdb1KNaRfQ77fBYhWXAEMYLHXEkRw85BRgWUmxzi7QT6JGptyJiqVLk1niuwCXqd"} { amount: 38121000000000,
  address: 'dde4NHefkTHEExGvb4k75hafRRWiBCnwNfxGLreozwwcGp4nmvdi8AK9iL8qyYmu6W8ryKQuEiyxAFHqpBHjsqq138u97fMUF' } { amount: 34670000000000,
  address: 'ddcX7XTPBqhP2m58ZfC4SHYrjEEoJLSFjPVU2opxzfnxKhVQhUoK9s84Q3kTv8viLrTt9bPB1pNK8ePA4gJkxxwe2L1Fvnowv' } { amount: 19265000000000,
  address: 'ddcpWuWTgXkJCuH9ZpZWnjRrJLFLByxUsTh5C6gLrnWJHtX7cRSaBJw7ChEeuTEgvajc8xP2KoqAsARh3KpXBFsG1AAnLxKfL' }

WHY???

---

PS:config

```
"payments": {
    "enabled": true,
    "interval": 600,
    "maxAddresses": 10,
    "mixin": 5,
    "transferFee": 100000,
    "minPayment": 1000000000000,
    "maxTransactionAmount": 100000000000000,
    "denomination": 1000000000
},
```

**Comment by fancoder** [comment]
I don't know what does it mean. Try yo decrease `"mixin": 5,` to `"mixin": 1,`.

**Comment by mapleshadow** [comment]
System has prompted not enough outputs to mix。
Why should the value of the lower?

**Comment by fancoder** [comment]
Just try it. There is a chance that it will helps.

**Comment by mapleshadow** [comment]
Indeed ~ ~ ~

2014-09-01 23:51 GMT+08:00 fancoder notifications@github.com:

> Just try it. There is a chance that it will helps.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fancoder/cryptonote-universal-pool/issues/21#issuecomment-54074016
> .

## 

—枫影—
