### ISSUE TITLE
Block unlocker died

### ISSUE THREAD

**Issue by exploshot** [fancoder/cryptonote-universal-pool#64]
![image](https://user-images.githubusercontent.com/9617859/32671426-a817ad64-c647-11e7-932e-e891516dfd41.png)

I think thats not correct, how can i fix this?

**Comment by wanda7566** [comment]
just change async version to 1.5.2 and redis version to 0.12.1 on your package.json, delete node_modules and run npm_update

**Comment by nidscom** [comment]
awesome. its working. Thanks 🤘

**Comment by exploshot** [comment]
I got it with node 0.10.42 or 0.10.43. But i forgot to mention it here and close the issue, sry my fault.
