### ISSUE TITLE
"Current Effort To Next Block" is ambiguous

### ISSUE THREAD

**Issue by faissaloo** [fancoder/cryptonote-universal-pool#71]
For a while I misinterpreted it as meaning 'how much effort is left' rather than 'how much effort has been expended so far'. I would appreciate better wording such as 'Current Effort Towards Next Block'

**Comment by leisegang** [comment]
Where is this function referenced?

**Comment by faissaloo** [comment]
On the front page

**Comment by leisegang** [comment]
Do you have a link because i cannot find anything with "effort"

**Comment by faissaloo** [comment]
I think I have the wrong repo, sorry.

**Comment by leisegang** [comment]
Which repo were you thinking about then?

**Comment by faissaloo** [comment]
Whatever aeonhash.com is using

**Comment by leisegang** [comment]
AH, that function. Thats not that hard implementing.

around line 100 in the home.html add this where you can find this(<div class="col-md-4 stats">). add after the pool fee for example.

`
        <div><i class="fa fa-users"></i> Round hashes: <span id="poolRoundHashes"></span></div>
	    <div><i class="fa fa-star-half-o"></i>Current Block Effort: <span id="currentEffort"></span></div>
	            <div>
`

add this after (updateText('poolMiners') or uncomment
            `updateText('poolRoundHashes', lastStats.pool.roundHashes.toString());`



update this after (updateText('lastHash')
`updateText('currentEffort', (lastStats.pool.roundHashes / lastStats.network.difficulty * 100).toFixed(1) + '%');`
