### ISSUE TITLE
Error after start of:    node init.js

### ISSUE THREAD

**Issue by coinsinternet** [fancoder/cryptonote-universal-pool#80]
### Hi, 
When do i start   node init.js,  the  screen is "freezing" - no data is shown for about 2-3 minutes. 
And there is no any data shown in the WEBsite after few tests. What do i miss? How can resolve it ?
At the end Ubuntu shows next error:

node init.js
Error: Redis connection to 10.42.0.4:6379 failed - connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

==============
FYI : here are my settings 

> {
>     "coin": "ducknote",
>     "symbol": "XDN",
>     "coinUnits": 100000000,
>     "coinDifficultyTarget": 240,
> ..............
> ..............
>   "daemon": {
>         "host": "10.42.0.4",
>         "port": 42081
>     },
>     "wallet": {
>         "host": "10.42.0.4",
>         "port": 8082
>     },
>     "redis": {
>         "host": "10.42.0.4",
>         "port": 6379,
>         "auth": null
>     },
>      "monitoring": {
>         "daemon": {
>             "checkInterval": 60,
>             "rpcMethod": "getblockcount"
>         },
>         "wallet": {
>             "checkInterval": 60,
>             "rpcMethod": "getbalance"
>         }
>     },

==============

**Comment by coinsinternet** [comment]
This issue has been resolved.

**Comment by coinsinternet** [comment]
Its been resolved

**Comment by somvannda** [comment]
how to resolve this?

**Comment by yordadev** [comment]
how to resolve this ?
