### ISSUE TITLE
Unlocker and payments not sending payments to miners?

### ISSUE THREAD

**Issue by cryptonoteminingpool** [fancoder/cryptonote-universal-pool#84]
Hello.

My pool has found a block but the miners have not received any balance or payment.

All of the miners appear with no pending or paid balance, and I can't understand why this hasn't been processed.

The pool info log shows that the block was found: https://snag.gy/HcxiQW.jpg

I have checked in the administration that the balance is already available.

In the unlocker log, I see that the block seems to have been unlocked already: https://snag.gy/bW1Fov.jpg

In the payments log I see messages saying that the payment threshold for the users has not been reached: https://snag.gy/8SKjfT.jpg

I have set in the config file for the pool the minimum values for payment as being 5:
https://snag.gy/znVCes.jpg
Here is the output I see on the site: https://snag.gy/dcgAaf.jpg

Am I missing something here, or is there anything not working in the payments module?

Thank you.

**Comment by xnakxx** [comment]
just a shot in the dark.... further down in the config file under 'users' are payments enabled? I have just setup an AEON pool and yet to hit a block and hope I don't run into the same situation

**Comment by cryptonoteminingpool** [comment]
There were actually several problems.

First, the payments node module had an error that needed to be fixed, then I had to regenerate all of the hashes from the users regarding that round, after generating the hashes the total amount would exceed the block reward to I had to manually reduce the hashcount proportionally until it equaled the amount of the block rewards, and finally there was a problem with the number of mixins that was to high to perform the transaction.
