### ISSUE TITLE
Block unlocker died, spawning replacement : no payment

### ISSUE THREAD

**Issue by phil2cr** [fancoder/cryptonote-universal-pool#92]
Once the block was found, the Unlocker failed to make the payment.

The mesage was like this one :
Error: Object true has no method 'map'
at async.waterfall.orphanCommands (/home/pool/lib/blockUnlocker.js:100:40)
at nextTask (/home/pool/node_modules/async/dist/async.js:5021:18)
at /home/pool/node_modules/async/dist/async.js:5015:17
at /home/pool/node_modules/async/dist/async.js:339:31
at /home/pool/node_modules/async/dist/async.js:847:20
at /home/pool/lib/blockUnlocker.js:92:17
at /home/pool/node_modules/async/dist/async.js:486:20
at /home/pool/node_modules/async/dist/async.js:3306:17
at /home/pool/node_modules/async/dist/async.js:952:25
at iteratorCallback (/home/pool/node_modules/async/dist/async.js:995:17)
Block unlocker died, spawning replacement...

The pool is running on Ubuntu 16.04.3 LTS
- node –version v0.10.48
- npm –version v2.15.1

**Comment by phil2cr** [comment]
Also i got : 
>
cd /home/user
npm ls async -g
async 1.5.2

cd pool
>in the pool
npm ls async
async 2.6.0

**Comment by phil2cr** [comment]
i put async="1.5.2" in
/home/user/pool/package.js

but i don't know what to do after ? i have to do npm again ?

**Comment by phil2cr** [comment]
function(blocks, callback){

        var redisCommands = 
Problem here ? - > blocks.map(function(block){
return ['hgetall', config.coin + ':shares:round' + block.height];
});

I understand "true" was passedd as an object in blocks and that make the problem ?

**Comment by mattgoody** [comment]
i was able to fix this by removing async 2.x.x and installing async 1.x.x

in your case in the pool i guess

**Comment by roshljo** [comment]
How exactly you remove async and install the other version in the pool?
Sorry for the dumb question, I am rather new to linux....

**Comment by phil2cr** [comment]
@roshljo  :) no question is dumb... sometime the answer could be :)
.
For Ubuntu 16.4.03 LTS (i cannot tell for other versions)
You have to go to your pool directory: cd /you_pool_directory
and : 
1) In package.json
check for
"async": "1.5.2",
if not change it

2) npm uninstall async

3) npm install async@1.5.2

4) check with
npm ls async

5) restart node init.js

**Comment by phil2cr** [comment]
@mattgoody Yes thanks for your answer
